# Generated by Django 4.0.2 on 2022-04-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanash', '0002_comments_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
