# Generated by Django 4.0.2 on 2022-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanash', '0003_alter_posts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes_count',
            field=models.IntegerField(default=1),
        ),
    ]
